# Numpy review homework

1. Make a numpy matrix from a Python list of lists...

In [11]:
import numpy as np 

list_of_lists = [[1, 1, 1], [2, 2, 2], [3, 3, 3], 
                  [4, 4, 4], [5, 5, 5]]

matrix = np.array(list_of_lists)

print(matrix)

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]


2. Make a 3D numpy matrix from a Python list of lists of lists!

In [13]:
nested_list = [[[1, 10, 14, 30], [2, 19, 24, 33], [9, 23, 11, 12]],
               [[6, 14, 20, 19], [25, 18, 21, 0], [7, 22, 3, 30]]]

matrix = np.array(nested_list)

print(matrix)

[[[ 1 10 14 30]
  [ 2 19 24 33]
  [ 9 23 11 12]]

 [[ 6 14 20 19]
  [25 18 21  0]
  [ 7 22  3 30]]]


3. Create a 5x3 array of Gaussian random numbers. 

In [14]:
random_nums = np.random.randn(5,3)
print(random_nums)

[[ 0.64001319 -0.56976269 -1.98592076]
 [-1.34885722 -0.29333753 -0.91941385]
 [-0.48032445  0.19431185  0.47163618]
 [ 0.25680884  1.84791802  0.15802919]
 [-1.49810906 -0.74920353 -1.5084607 ]]


4. Write a script to go through the array created in 3. and announce (print) the value and its row and column indexes.

Hint: Use nested `for` loops - one to loop through the rows and one to loop through the columns.

In [16]:
array_nums = [[ 0.64001319, -0.56976269, -1.98592076],
 [-1.34885722, -0.29333753, -0.91941385],
 [-0.48032445, 0.19431185, 0.47163618],
 [ 0.25680884, 1.84791802, 0.15802919],
 [-1.49810906, -0.74920353, -1.5084607 ]]


for i in range(len(array_nums)):
    for j in range(len(array_nums[i])):
        print(f"Value: {array_nums[i][j]}, Row Index: {i}, Column Index: {j}")

Value: 0.64001319, Row Index: 0, Column Index: 0
Value: -0.56976269, Row Index: 0, Column Index: 1
Value: -1.98592076, Row Index: 0, Column Index: 2
Value: -1.34885722, Row Index: 1, Column Index: 0
Value: -0.29333753, Row Index: 1, Column Index: 1
Value: -0.91941385, Row Index: 1, Column Index: 2
Value: -0.48032445, Row Index: 2, Column Index: 0
Value: 0.19431185, Row Index: 2, Column Index: 1
Value: 0.47163618, Row Index: 2, Column Index: 2
Value: 0.25680884, Row Index: 3, Column Index: 0
Value: 1.84791802, Row Index: 3, Column Index: 1
Value: 0.15802919, Row Index: 3, Column Index: 2
Value: -1.49810906, Row Index: 4, Column Index: 0
Value: -0.74920353, Row Index: 4, Column Index: 1
Value: -1.5084607, Row Index: 4, Column Index: 2


5. Make an new array out of your random numbers such that the mean is 10 and the standard deviation is 3.

In [34]:
# desired mean and standard deviation
mean = 10
std = 3

# calculate current mean and standard deviation of the random nums
current_mean = np.mean(array_nums)
current_std = np.std(array_nums)

# switch the random numbers to have desired mean and standard deviation
switched_nums = desired_mean + (desired_std / current_std) * (array_nums - current_mean)

print(switched_nums)

[[13.15405396  9.43380967  5.07890886]
 [ 7.03797585 10.28385896  8.35857933]
 [ 9.70884583 11.78345475 12.63626912]
 [11.97564247 16.86854449 11.67188007]
 [ 6.57900381  8.88200188  6.54717094]]


6. Count the number of values in your new array that are below 7.

In [30]:
count_below_7 = np.count_nonzero(switched_nums < 7)

print("Number of values below 7:", count_below_7)

Number of values below 7: 3


7. Make a numpy sequence that has the even numbers from 2 up to (and including) 20.

In [21]:
even_sequence = np.arange(2, 21, 2)

print(even_sequence)

[ 2  4  6  8 10 12 14 16 18 20]


8. Get the second and third rows of your array created in #5.

In [31]:
second_third_rows = switched_nums[1:3]

print(second_third_rows)

[[ 7.03797585 10.28385896  8.35857933]
 [ 9.70884583 11.78345475 12.63626912]]


9. Compute the mean of the columns of your array created in #5.

In [33]:
mean_cols = np.mean(switched_nums, axis=0)

print("Mean of the columns:", mean_cols)

Mean of the columns: [ 9.69110438 11.45033395  8.85856167]
